version: "3.9"

services:
  tpj_db:
    container_name: tpj_db
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: travelers_db
      MYSQL_USER: teamproject
      MYSQL_PASSWORD: teamproject
      MYSQL_ROOT_PASSWORD: khWeb@123
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
